Repository sakoki/Rushhour, pull requests merged in 2019-04, with the labels that each got.

#25 Exploratory data analysis
  .gitignore
  code/playground/DMD.ipynb
  code/playground/LSTM_single_input.ipynb
  code/playground/exploratory_analysis.ipynb
  code/playground/region_mapper.ipynb
  code/playground/tweet_mapper.ipynb
  code/utils/api.py
  code/utils/graph.py
  code/utils/traffic_processing.py
  code/utils/twitter_processing.py
  output/census.gpickle
  output/census_filtered.gpickle
  output/region_by_time_series.csv
  output/region_time_series_filtered.csv
  output/region_weights.csv
  output/region_weights.p
  temp_data/code_by_vehicle_name(edited).csv
Labels: enhancement

#27 Pipeline lstm
  code/README.md
  code/gen_region_files.py
  code/models/lstm_baseline.py
  code/utils/graph.py
  code/utils/model_data_prep.py
  code/utils/traffic_processing.py
Labels: enhancement

#28 save fig & corperate with filtered data
  code/models/lstm_baseline.py
Labels: enhancement

#29 Pipeline arima
  code/models/ARIMA_baseline.py
  code/models/lstm_baseline.py
  code/utils/toolkit.py
  code/utils/traffic_processing.py
Labels: enhancement

#30 move weighted average function into utils/model_data_prep.py
  code/models/ARIMA_baseline.py
  code/utils/model_data_prep.py
Labels: enhancement

#31 fix weighted avg bug
  code/models/ARIMA_baseline.py
  code/models/lstm_baseline.py
  code/utils/model_data_prep.py
Labels: bug

#32 Tweet processing
  .gitignore
  code/playground/LSTM_single_input.ipynb
  code/playground/tweet_filtering.ipynb
  code/playground/tweet_mapper.ipynb
  code/utils/api.py
  code/utils/twitter_processing.py
  output/tweet_features_by_hour.csv
Labels: enhancement

#33 Lstm multi model
  code/models/ARIMA_baseline.py
  code/models/lstm_baseline.py
  code/models/lstm_multi_baseline.py
  code/utils/model_data_prep.py
  output/loss_lstm.png
  output/mae_lstm.png
Labels: enhancement

#35 Lstm with nb
  code/models/lstm_nb.py
  code/utils/graph.py
  code/utils/model_data_prep.py
Labels: bug, enhancement

#37 Clean result dir
  code/models/lstm_baseline.py
  graph/loss_lstm.png
  graph/mae_lstm.png
  logs/arima.log
  logs/lstm_1model_1region.txt
Labels: bug, enhancement

#38 Lstm twitter
  code/models/lstm_twitter.py
  logs/lstm_baseline.log
  logs/results.md
Labels: enhancement

#39 Lstm twitter
  code/models/lstm_baseline.py
  code/models/lstm_multi_nb.py
  code/models/lstm_twitter.py
  code/playground/lstm_pipeline_test.ipynb
  code/utils/model_data_prep.py
  logs/lstm_multi_nb_combine.txt
Labels: enhancement

#40 Model tuning
  code/utils/model_data_prep.py
  graph/lstm_loss3layerWith8units_batch64_.png
  graph/lstm_loss3layerWith8units_batch64_ordered.png
  graph/lstm_mae3layerWith8units_batch64_.png
  graph/lstm_mae3layerWith8units_batch64_ordered.png
  graph/resample_test_base.png
  graph/resample_test_base_mae.png
  logs/3layerWith8units_batch64_ordered.log
  logs/3layerWith8units_batch64_ordered1.log
  logs/3layerWith8units_batch64_randSampled.log
  logs/3layerWith8units_batch64_randSampled1.log
  logs/lstm_baseline_resample_test.log
  logs/lstm_multi_nb-1-114.log
  logs/lstm_multi_nb.log
  logs/lstm_multi_nb_115-end.log
  output/arima_MAE_regions.csv
  output/arima_MAE_regions.p
Labels: enhancement

#41 Model tuning
  code/models/lstm_baseline.py
  code/playground/lstm_pipeline_test.ipynb
  code/utils/model_data_prep.py
  graph/lstm_loss2layerWith16units_batch64_ordered.png
  graph/lstm_loss2layerWith16units_batch64_ordered_viz.png
  graph/lstm_mae2layerWith16units_batch64_ordered.png
  graph/lstm_mae2layerWith16units_batch64_ordered_viz.png
  logs/lstmbase_viz.log
  output/lstm_Y.p
  output/lstm_predict.p
Labels: enhancement

#42 update results for viz
  output/lstm_MAE_regions.csv
  output/lstm_MAE_regions.p
Labels: enhancement
